/* The directory: every site collected from the source posts.
   To add a site, append { name, site, handle } — `site` has no protocol, `handle` has no @. */
const SITES_DATA = [
  { name: "John Hanacek", site: "johnhanacek.com", handle: "johnhanacek" },
  { name: "PravarPrasad", site: "pravar.design", handle: "pravarprasad" },
  { name: "Tushit", site: "tushitgarg.com", handle: "TushitGargg" },
  { name: "انضمام الحق", site: "inzemam.tech", handle: "c0nd0r1n3e94" },
  { name: "Mrinal", site: "mrinals-vault.xyz", handle: "Hi_Mrinal" },
  { name: "Seymen Şimşek", site: "seymensimsek.com", handle: "seymensimsekk" },
  { name: "mikey", site: "mikes.cv", handle: "mjbarton_" },
  { name: "Ankit Pandey", site: "ankitpandey19.vercel.app", handle: "ankitpandey190" },
  { name: "Vishal Singh", site: "vishaal21.github.io/Portfolio", handle: "singhvishaal21" },
  { name: "Hritik Yadav", site: "hritik.online", handle: "Hritik_Yadav_1" },
  { name: "Kushagra", site: "thesynthax.space", handle: "thesynthaxx" },
  { name: "mehek", site: "mehekprabhakar.com", handle: "mehekprabhakar" },
  { name: "Anvi Saini", site: "anvisaini.com", handle: "tooanvi" },
  { name: "Boobesh AG", site: "boobesh-portfolio-three.vercel.app", handle: "buildwithboo" },
  { name: "Elias Simojoki", site: "elias.simojoki.dev", handle: "elias_simojoki" },
  { name: "Haseeb Mir", site: "haseeb-mir.vercel.app", handle: "HaseebMir91" },
  { name: "probiex007", site: "akshatnaruka.github.io/Portoflio", handle: "probiex007" },
  { name: "Raunaq", site: "raunaqness.com", handle: "raunaqness" },
  { name: "John Rodrigues", site: "john-rodrigues.com", handle: "john_rodrigues_" },
  { name: "Vancis", site: "vanpics.pages.dev", handle: "Vancis5" },
  { name: "Defi Preacher", site: "femdev.site", handle: "DefiPreacherr" },
  { name: "codiac", site: "codiac.online", handle: "musa_codes" },
  { name: "Raufan", site: "muhraufan.com", handle: "muhraufan" },
  { name: "Priyal Raj", site: "priyalraj.com", handle: "Capta1nCodes" },
  { name: "Adeel Imran", site: "adeelhere.com", handle: "adeelibr" },
  { name: "Husain", site: "husainjhalod.me", handle: "husain_j53" },
  { name: "phatg", site: "yyyyaaa.com", handle: "phatggg" },
  { name: "Harshal", site: "harshalranjhani.in", handle: "ranjhaniharshal" },
  { name: "Aditya Dutt Pandey", site: "adpandey.dev", handle: "adp_alpha" },
  { name: "Jad", site: "jadmadi.net", handle: "JadMadi" },
  { name: "Blake", site: "blakecrosley.com", handle: "BlakeC" },
  { name: "mohamedation", site: "mohamedation.com", handle: "mohamedation" },
  { name: "Henry", site: "hendrikrenken.de", handle: "henrynekner" },
  { name: "Oreọfẹ", site: "thedanieloreofe.xyz", handle: "Thedanieloreofe" },
  { name: "nate", site: "nates-software.com", handle: "natemcguire" },
  { name: "ajeesh", site: "ajeesh.xyz", handle: "ajeeshRS_" },
  { name: "Parv", site: "parvsondhi.com", handle: "ParvSondhi" },
  { name: "Rahul Rao", site: "houseoflux.in", handle: "out_oflux" },
  { name: "supreme", site: "oluwatosin.io", handle: "supreme_io" },
  { name: "Siji", site: "siji-ibukun.com", handle: "Siji_Ibukun" },
  { name: "Adarsh Swaminath", site: "adarshswaminath.github.io", handle: "AdarshS002" },
  { name: "Mohit Bhandari", site: "mohitbhandari.vercel.app", handle: "MohitDev45" },
  { name: "Swami", site: "swamii.me", handle: "SwamiMalode" },
  { name: "Aarti", site: "aartiutwani.com", handle: "Aartiutwani" },
  { name: "E. Emmmah", site: "emmah.xyz", handle: "hey_emmah" },
  { name: "Devsigner", site: "devadhathan.com", handle: "MDdevaD" },
  { name: "Big Sheddy", site: "sheddy.xyz", handle: "coder_blvck" },
  { name: "Rachit Dhaka", site: "rachitdhaka.me", handle: "rachitdhaka_" },
  { name: "Knup", site: "knup.com", handle: "RyanKnuppel" },
  { name: "nick (ник)", site: "nick-price.uk", handle: "nick__price__" },
  { name: "Joseph Brendon", site: "josephbrendon.in", handle: "brejofit" },
  { name: "Ayoola Tosin", site: "ayoolatosin.work", handle: "ayoolatosinn" },
  { name: "Antidote", site: "2030.tech", handle: "AxelMtbr" },
  { name: "Adnan", site: "adnan-itis.github.io/personalwebsite", handle: "Adnan7746965226" },
  { name: "Ali-en", site: "aaali.xyz", handle: "alien69" },
  { name: "Bibi", site: "rebeccaboluwatife.framer.website", handle: "bibi_427" },
  { name: "shubh", site: "shubhamraut.tech", handle: "ifeelProxim" },
  { name: "Max", site: "maxdhindsa.com", handle: "dhizdsa" },
  { name: "Eduardo de Cesaro", site: "cesaroeduardo.com", handle: "reidophotoshops" },
  { name: "Andrei", site: "andreinasonov.com", handle: "nsnvandrey" },
  { name: "shashwa7", site: "shashwa7.in", handle: "offcod8" },
  { name: "Devanshu", site: "devanshusharma.com", handle: "DevanshuXi" },
  { name: "Benjamin", site: "bma.sh", handle: "BenjamMartin" },
  { name: "Bhavesh Singhal", site: "bhavesh.recso.dev", handle: "descentkatil_" },
  { name: "Sankalp Shukla", site: "sankalp.pro", handle: "yuppsankalp" },
  { name: "Purshottam", site: "purshottam.dev", handle: "ThinkMo60778392" },
  { name: "Suhail Roushan", site: "suhailroushan.com", handle: "0xsuhailroushan" },
  { name: "SimonAKing", site: "simonaking.com", handle: "simon_aking" },
  { name: "Jessin Sam S", site: "jessinsam.com", handle: "jessinvibe" },
  { name: "Armaan", site: "armaann.com", handle: "armaanhq" },
  { name: "Suraj Mandal", site: "mandalsuraj.com", handle: "surajmandalcell" },
  { name: "Abhijeet Gautam", site: "abhijeetgautam.in", handle: "abhijeet_gautam" },
  { name: "Ganesh Kumar", site: "bellkiosk.website", handle: "ganeshahaa" },
  { name: "Jose Moreno", site: "13doots.com", handle: "13doots" },
  { name: "longjohn", site: "orevbajohn.me", handle: "orevbajohn_" },
  { name: "Valerian Pereira", site: "valerianpereira.in", handle: "valerianper_era" },
  { name: "Mayank", site: "m4yank.com", handle: "MayankK51049579" },
  { name: "Filip Vabroušek", site: "filipvabrousek.com", handle: "filipvabrousek" },
  { name: "jaack", site: "jaack.me", handle: "ijaack94" },
  { name: "Mrityunjay", site: "mrityunjay.site", handle: "mrityunjay_18" },
  { name: "shrawberry", site: "shravani.design", handle: "shrawberryy" },
  { name: "Abdelrhman Said", site: "abdelrhmansaid.com", handle: "AbdelrhmanSWE" },
  { name: "Meet Patel", site: "meetpat-os.vercel.app", handle: "meetp_4071" },
  { name: "Sudaksh Soti", site: "sudaksh.io", handle: "maybesudaksh" },
  { name: "Kunal Gosrani", site: "kunalgosrani.com", handle: "_kunal_gosrani" },
  { name: "Eeshan", site: "eeshan89.wordpress.com", handle: "notesundrground" },
  { name: "reaper", site: "reaper.is", handle: "barelyreaper" },
  { name: "Tejas Kumar", site: "tej.as", handle: "TejasKumar_" },
  { name: "Chánh Đại", site: "chanhdai.com", handle: "iamncdai" },
  { name: "Max Rovensky", site: "maxrovensky.com", handle: "MaxRovensky" },
  { name: "Feruz Karimov", site: "feruz-karimov.dev", handle: "feruzkrm" },
  { name: "Peter", site: "miloszewski.net", handle: "miloszewski" },
  { name: "Nishant", site: "dawgdevv.tech", handle: "sfunish" },
  { name: "Kumar Shivam", site: "portfolio-frontend-pearl-rho.vercel.app", handle: "KShivam62684" },
  { name: "sagar", site: "sagarck.com", handle: "sagarck04" },
  { name: "Taimoor Nasir", site: "taimoornasir.com", handle: "taimoor_nasir1" },
  { name: "Amrith", site: "amrith.co", handle: "amrith" },
  { name: "melih", site: "meliharik.dev", handle: "melihify" },
  { name: "Omoba Bello", site: "belloopeyemi.com", handle: "omoba_bello" },
  { name: "Abdelrahman", site: "abdrizik.com", handle: "abderizik" },
  { name: "Shardul", site: "shardul.studio", handle: "pracosm" },
  { name: "Revanth Krishna", site: "revanthkrishna.com", handle: "Revanthkrishna_" },
  { name: "Flavius", site: "flavius.pro", handle: "flaviuscj1" },
  { name: "Sunghyun Cho", site: "cho.sh", handle: "anaclumos" },
  { name: "Josh", site: "joshnr.com", handle: "joshnr" },
  { name: "Prithvi", site: "prithvibharadwaj.com", handle: "PrithviBtw" },
  { name: "Semih", site: "hsemihaktas.vercel.app", handle: "hsemihaktas" },
  { name: "KiraMyao", site: "kiramyao.com", handle: "KiraMyao" },
  { name: "Ivan Golovach", site: "ivan.ge", handle: "ivandotge" },
  { name: "Asim", site: "asimkhaskheli.vercel.app", handle: "asim_ismail_" },
  { name: "Kris Puckett", site: "krispuckett.com", handle: "krispuckett" },
  { name: "Arie", site: "ariestwn.com", handle: "nwtseira" },
  { name: "govi", site: "govijr.vercel.app", handle: "kirtandopamine" },
  { name: "Deepak Sharma", site: "deepakbuilds.com", handle: "heydeepak92" },
  { name: "Obaid Ahmed", site: "obaid.dev", handle: "obaid" },
  { name: "Rakshit", site: "rakshitsisodiya.xyz", handle: "brucewayne_9901" },
  { name: "Ruturaj", site: "ruturajbayad.in", handle: "rutu_3" },
  { name: "Suhassai Masetty", site: "suhassai.online", handle: "suuuuuuhas" },
  { name: "Baba", site: "madebyaditya.vercel.app", handle: "HitoritabiBaba" },
  { name: "Yannick Kouakou", site: "yannickkouakou.com", handle: "baby_desiigner" },
  { name: "Lucas", site: "lucasamarale.dev", handle: "LucasamaraleDev" },
  { name: "Ben Mo", site: "benmodev.co", handle: "benmodev" },
  { name: "Sadiq", site: "sadiq.tech", handle: "Md_Sadiq_Md" },
  { name: "segun.", site: "segun.dev", handle: "tuasegun" },
  { name: "Pratham Jindal", site: "pratham.me", handle: "prathamdesigns" },
  { name: "Vasco", site: "vascodegraaff.com", handle: "vascodegraaff" },
  { name: "Tobiloba Sulaimon", site: "tobilobasulaimon.com", handle: "tobilobaCodes00" },
  { name: "Nicolas Grenié", site: "nicolasgrenie.com", handle: "picsoung" },
  { name: "Daniel Olowoniyi", site: "danielolowoniyi.com", handle: "iamdanztee" },
  { name: "Val", site: "lele-studio.com", handle: "valerieWeb3" },
  { name: "Dawn Saju", site: "dawnsaju.dev", handle: "DawnSaju7" },
  { name: "Christian Weichel", site: "csweichel.de", handle: "csweichel" },
  { name: "eigenesis", site: "eigenesis.org", handle: "eigengenesis" },
  { name: "Prakash Pawar", site: "thevenice.in", handle: "Thevenicelive" },
  { name: "Om", site: "piunknown.dev", handle: "piunknown043" },
  { name: "Sandeep", site: "sandeep.design", handle: "sandeepxdesign" },
  { name: "Adarsh Bhardwaj", site: "adarshbhardwaj.space", handle: "adarshdevs" },
  { name: "Aditya", site: "adityalogs.xyz", handle: "adityawaslost" },
  { name: "random guy on the internet", site: "devkharay.com", handle: "KharayKrayKray" },
  { name: "Belabbas Anis", site: "bmudpt.xyz", handle: "0xBelabbaa" },
  { name: "FINNSK", site: "finnsk.com", handle: "FINNSK_" },
  { name: "Manan", site: "manan-os.vercel.app", handle: "manan_suneja" },
  { name: "Shivam Taneja", site: "theguyshetoldyouabout.com", handle: "codesbyshivam" },
  { name: "Agustín Garate", site: "agustingarate.com", handle: "garate__" },
  { name: "IroncladDev", site: "ironclad.sh", handle: "IroncladDev" },
  { name: "Adar", site: "adar2378.com", handle: "adar2378" },
  { name: "Krishna G", site: "krishnaganga.pages.dev", handle: "KrishnaG1703" },
  { name: "inker", site: "inkerspeak.com", handle: "inkerlingo" },
  { name: "Toryn", site: "toryn.bio", handle: "tttorynnn" },
  { name: "Alex Tudun", site: "alextudun.com", handle: "AlexTudun" },
  { name: "aditya", site: "naw.al", handle: "naawwwal" },
  { name: "Sagar", site: "sarlloc.com", handle: "sarlloc" },
  { name: "Carter", site: "carterkowang.com", handle: "CarterKoWang" },
  { name: "Kartik", site: "kartiklabhshetwar.com", handle: "code_kartik" },
  { name: "lotamchi", site: "lottabydesign.xyz", handle: "lottabydesign" },
  { name: "eponmidun okomitobigan", site: "ayomidelawal.space", handle: "adesolayomii" },
  { name: "byeval", site: "letters.byeval.com", handle: "xbyeval" },
  { name: "Manas Mahodaya", site: "mansmahodaya.com", handle: "Introducejobs" },
  { name: "Mark Bowley", site: "bestpersonalwebsite.com", handle: "markbowley" },
  { name: "Mo", site: "mo.software", handle: "Megootronic" },
  { name: "Arne", site: "arnekellmann.de", handle: "arnekellmann" },
  { name: "tom", site: "tomm.page", handle: "tomm_ui" },
  { name: "Elsa", site: "elsas-portfolio.framer.website", handle: "Elsalearns" },
  { name: "Leo", site: "leandropiccione.com", handle: "piccionenter" },
  { name: "Ateendra", site: "ateendra.dev", handle: "ateendra24" },
  { name: "Marouane Gazouzi", site: "gazouzi.com", handle: "marouanegazouzi" },
  { name: "Ernesto Eduardo", site: "ernestoeduardo.com", handle: "eedobarganes" },
  { name: "Ekki Syam", site: "testingwithekki.com", handle: "ekkisyam2310" },
  { name: "Sarthak", site: "portfolio-web-theta-bay.vercel.app", handle: "imtherealsg" },
  { name: "Liam", site: "liaminit.com", handle: "liammdevs" },
  { name: "ezekiel", site: "aaezekiel.co", handle: "aaezekiel_co" },
  { name: "JB", site: "joshuaanthony.design", handle: "_Joshuaanthony" },
  { name: "Edoardo Lunardi", site: "edoardolunardi.dev", handle: "edo_lunardi" },
  { name: "Jeremiah Chienda", site: "chienda.com", handle: "liwucodes" },
  { name: "Cobbinah", site: "mrcobbinah.vercel.app", handle: "ECobbinah44868" },
  { name: "Denzel", site: "chideraokonkwo.com", handle: "0xDenzel" },
  { name: "Shanny", site: "shanny.design", handle: "Itshanny01" },
  { name: "Sony AK", site: "sony-ak.com", handle: "tpozbl" },
  { name: "Saurabh Sharma", site: "srbh.site", handle: "srbh_here" },
  { name: "Shubham Sharma", site: "subham22.is-a.dev", handle: "subhamk12" },
  { name: "Luca", site: "gianlucreates.com", handle: "_lucaDesign" },
  { name: "Blaze", site: "blaze.design", handle: "0xblz" },
  { name: "Aayan Agarwal", site: "aayanagarwal.com", handle: "aayan1405" },
  { name: "Daniel Orubo", site: "thecontentnerd.com", handle: "NerdEfiko" },
  { name: "sammwy", site: "sammwy.com", handle: "sammwy" },
  { name: "Creative Missionary", site: "iotukoya.framer.website", handle: "iotukoya" },
  { name: "Tunan", site: "orionchen.me", handle: "orion_c29" },
  { name: "Mohit Singh", site: "mohitsingh.cloud", handle: "CalmNrd" },
  { name: "Conor", site: "conr.dev", handle: "conrdotdev" },
  { name: "Marko Vurnek", site: "vurnek.com", handle: "markovurnek_" },
  { name: "Tomiwa Akanbi", site: "tomiwaakanbi.com", handle: "akanbitomjoe" },
  { name: "Anzal Husain Abidi", site: "anzalabidi.dev", handle: "AnzalAbidi" },
  { name: "Chloe", site: "chloevalesquez.vercel.app", handle: "chloevalesquez" },
  { name: "batuhan içöz", site: "bt.hn", handle: "batuhan" },
  { name: "Dhruv Pradeep", site: "dhruvpradeep.in", handle: "dhruvprad" },
  { name: "Brandon Davenport", site: "itsbrandond.com", handle: "itsbrandond" },
  { name: "Aman", site: "beingamanforever.github.io", handle: "beingamanFF" },
  { name: "Laiba Fareed", site: "laibafareed.com", handle: "Alilaiba10" },
  { name: "Nikhil Gumasta", site: "nikhil.is-a.dev", handle: "Nikkhil_g18" },
  { name: "Justin Rands", site: "jrands.com", handle: "jayrizpop" },
  { name: "Pranav Pawar", site: "pranavpawar.com", handle: "ByPranavPawar" },
  { name: "Habib", site: "habibthadev.tech", handle: "habibthadev" },
  { name: "Bhanu Prakash", site: "portfolio.bhanu.lol", handle: "Bhanuu_Prakash" },
  { name: "Matthew Yu", site: "matthewyu.dev", handle: "matthewyuart" },
  { name: "Aliou Ba", site: "aliouba.org", handle: "misteraliouba" },
  { name: "Dhanush Kandhan", site: "dhanu.letretro.com", handle: "akadhanu" },
  { name: "A Minimalist!", site: "vinayhulsurkar.netlify.app", handle: "hello_august24" },
  { name: "Emre Elbeyoglu", site: "elbeyoglu.com", handle: "elbeyoglu" },
  { name: "Stefan", site: "creativestefan.work", handle: "creativestefan" },
  { name: "Vasanth", site: "vasanthmuralidharan.com", handle: "vasanthroughput" },
  { name: "Nate", site: "nathantonani.com", handle: "nathantonani" },
  { name: "Manas", site: "manas-marathe.vercel.app", handle: "mauux0" },
  { name: "Onur Şuyalçınkaya", site: "onur.dev", handle: "onurschu" },
  { name: "ansh.a", site: "ansh.is-a.dev", handle: "vedolos" },
  { name: "Ali", site: "alicalimli.com", handle: "alicalimli_dev" },
  { name: "Mohamed Azzam", site: "heymo.work", handle: "esazzam" },
  { name: "Riddhi Gupta", site: "riddhi.life", handle: "theriddhigupta" },
  { name: "Rofeh", site: "pagurad.com", handle: "imrofeh" },
  { name: "Giuseppe Petrini", site: "sephmartin.com", handle: "sephmartinmusic" },
  { name: "Federico", site: "branca.si", handle: "brancasi" },
  { name: "Sevan Lewis-Payne", site: "sevanlewispayne.com", handle: "sevanlp" },
  { name: "Captain jay", site: "jaycaptain.xyz", handle: "captain0jay" },
  { name: "V", site: "whencut.in", handle: "_whencut" },
  { name: "Fabian Ernst", site: "fabian.ernst-kuehn.de", handle: "iamcuetime" },
  { name: "siddharth", site: "fiveconstants.com", handle: "sambharia" },
  { name: "Abishek Neupane", site: "abishekn.com.np", handle: "virtualabishek" },
  { name: "Preston", site: "prestonb.xyz", handle: "prestonb_xyz" },
  { name: "Indra55", site: "hitanshu.xyz", handle: "dev_hitanshu" },
  { name: "Samuel", site: "canvasofsam.pro", handle: "cnvs_sam" },
  { name: "Hovo Dallakyan", site: "hovo.me", handle: "hovdallakyan" },
  { name: "Shivam Itankar", site: "shivam230.github.io/commit-art", handle: "ShivamItankar02" },
  { name: "Long Wang", site: "cv.rocorgi.wang", handle: "wangdouglas" },
  { name: "Tom", site: "internethuman.neocities.org", handle: "tomismeta" },
  { name: "Rodrigo Dias", site: "rgo.pt", handle: "rodrgds" },
  { name: "Anurag", site: "anuragd.me", handle: "aarekaz" },
  { name: "Elisabeth", site: "elisabethnnamani.dev", handle: "elisynthdev" },
  { name: "Joe Hu", site: "hubeiqiao.com", handle: "hubeiqiao" },
  { name: "Michael Hungbo", site: "hungbo.dev", handle: "michaelhungbo" },
  { name: "Giordano de Pinho Souza", site: "giordanopsouza.com", handle: "Giordanopsouza" },
  { name: "Tim Wijnhoven", site: "superhuge.net", handle: "TimWijnhoven" },
  { name: "timour kosters", site: "timourkosters.com", handle: "timourxyz" },
  { name: "Victor", site: "enyinnaya.xyz", handle: "EnyitheDev" },
  { name: "Benjamin Balazs", site: "benjaminbalazs.com", handle: "benjaminbalazs" },
  { name: "Tej", site: "novacodes.dev", handle: "NovaCodesStuff" },
  { name: "ilyas", site: "fizzy.blog", handle: "farzeenilya" },
  { name: "Shaheer Ahmed", site: "shaheer.design", handle: "Boringcuriosity" },
  { name: "Katherine Dee", site: "defaultfriend.net", handle: "default_friend" },
  { name: "ubeydullah öz", site: "adamkarga.net", handle: "adamkarga_" },
  { name: "Luis Pablo Segovia", site: "luispablosegovia.dev", handle: "Manoloacademia1" },
  { name: "harshal.", site: "harshalvk.com", handle: "harshalvk_" },
  { name: "Ujwal Mahajan", site: "ujwalmahajan.vercel.app", handle: "Ujwal_ai" },
  { name: "navya", site: "home.navyabijoy.tech", handle: "navyabijoy" },
  { name: "Poorvith M P", site: "poorvithmp.com", handle: "poorvith_mp" },
  { name: "Manas Choudhary", site: "manasdev.codes", handle: "_manaschoudhary" },
  { name: "RAVI RAGHUL", site: "raviraghul.me", handle: "RaviR_S" },
  { name: "Sumeet A.", site: "sumeetdesigns.com", handle: "designer_sda" },
  { name: "Joe Blau", site: "joeblau.com", handle: "joeblau" },
  { name: "Shivani Srivastava", site: "shivani.design", handle: "shi_illustrator" },
  { name: "seb-astian", site: "seb-astian.com", handle: "seb__design" },
  { name: "Narsi", site: "narsi.xyz", handle: "narsixyz" },
  { name: "samir", site: "samirkharel.com", handle: "samirmadeit" },
  { name: "matthew_cc", site: "matthewcc123.github.io", handle: "matthewcc245" },
  { name: "Bartlomiej Tyrpien", site: "tyrpien.com", handle: "bartlomein" },
  { name: "Slivereign", site: "slivereign.art", handle: "Slivereign" },
  { name: "Ren", site: "perezbartra.com", handle: "agua90era" },
  { name: "Nishant Modi", site: "nishantmodi.me", handle: "nishantmodi3105" },
  { name: "Evan Applegate", site: "nicemaps.evanapplegate.com", handle: "youwillmakemaps" },
  { name: "Junqi", site: "junqi.me", handle: "junqi_k" },
  { name: "Guille", site: "guilleigmu.com", handle: "guille_igmu" },
  { name: "Mohd Aadil", site: "mohdmashi.netlify.app", handle: "mohdmashiullah" },
  { name: "Aaditya Raul Lobo", site: "kai.aadityalobo.com", handle: "aadityalobo" },
  { name: "Drew", site: "drewsully.com", handle: "Drew_Sully" },
  { name: "Mark Shenouda", site: "markcodes.dev", handle: "MarkSShenouda" },
  { name: "Muzzamil Ahmed Khan", site: "muzzamilahmedkhan.site", handle: "muzzamilahmedkh" },
  { name: "OPM", site: "mihircodes.in", handle: "mihirtwt" },
  { name: "Renée", site: "reneeshaw.co", handle: "pollyfockit" },
  { name: "Emmanuel Kokele", site: "kokele.waghitech.com", handle: "EKokele" },
  { name: "Hardick Raj", site: "hardickraj.in", handle: "hardickraj" },
  { name: "Sayan Gupta", site: "sayangupta.in", handle: "Sayan_shanky" },
  { name: "Rishwajeet", site: "rishwajeetsingh.com", handle: "rjrazzle" },
  { name: "Robert DeVore", site: "robertdevore.com", handle: "deviorobert" },
  { name: "Eugene Voroniuk", site: "eugenevoroniuk.com", handle: "ai_euge" },
  { name: "Clark", site: "clarkphan.dev", handle: "clarkphan" },
  { name: "Aniket Pawar", site: "aniketpawar.com", handle: "alaymanguy" },
  { name: "Simone Andreotti", site: "simone-dev.com", handle: "Simone_dev_com" },
  { name: "Aditya Mer", site: "adityamer.dev", handle: "mer_aditya" },
  { name: "anuragkrishh", site: "anuragkrishh.com", handle: "anuragkrishh" },
  { name: "Aswin Manohar", site: "aswinmanohar.com", handle: "Aswin_polymath" },
  { name: "Sakthimurugan S", site: "sakthimurugan.dev", handle: "sakthimurugans_" },
  { name: "Dominik", site: "acmdom.dev", handle: "Domvnxk" },
  { name: "Andy", site: "balogunoluwasogo.webflow.io", handle: "b_oluwasogo" },
  { name: "Surabhi", site: "surabhi.cv", handle: "surabhixyz" },
  { name: "bola.", site: "bola.pxxl.click", handle: "NathanOyewole" },
  { name: "Rehan", site: "rehanbuilds.xyz", handle: "MRehan_5" },
  { name: "Karan", site: "karan30.vercel.app", handle: "kwakhare5" },
  { name: "Diogo Neves", site: "diogoneves.com", handle: "DiogoSnows" },
  { name: "Paweł Ludwiczak", site: "plud.net", handle: "ludwiczakpawel" },
  { name: "Ryan Gilpatric", site: "ryangilpatric.com", handle: "RyanGilpatric" },
  { name: "mridul", site: "mridul.sh", handle: "rexmkv" },
  { name: "Kerem", site: "kerem.co", handle: "kerem" },
  { name: "Tejas Patil", site: "thetejaspatil.com", handle: "tejasdesigns" },
  { name: "akshat", site: "akshat.fyi", handle: "akshatswork" },
  { name: "Vin", site: "vinsen.framer.website", handle: "vinisdesigning" },
  { name: "Mike Legemah", site: "mleg.tech", handle: "TechFishBbq" },
  { name: "Karma", site: "shreyansh.is-a.dev", handle: "shreyansh_0x0_" },
  { name: "Michael Andreuzza", site: "michaelandreuzza.com", handle: "Mike_Andreuzza" },
  { name: "Kevin Thumbar", site: "kevinnn.xyz", handle: "kevinnn_tw" },
  { name: "Arnabjk", site: "arnabjk008.dev", handle: "Arnabjk008" },
  { name: "Abdullah", site: "abdullahtech.dev", handle: "abdullah_twt23" },
  { name: "ana howard", site: "ana.sh", handle: "AnaArsonist" },
  { name: "Dhanesh Shetty", site: "dhaneshshetty.in", handle: "DexExplorer14" },
  { name: "Tim", site: "timmadeit.com", handle: "timothyogundipe" },
  { name: "Valli Lakshmanan", site: "status-tbd.com", handle: "itsvalli" },
  { name: "Ben Kamens", site: "kamens.com", handle: "kamens" },
  { name: "Vyshak Iyengar", site: "vyshak.me", handle: "vyshakkiyengar" },
  { name: "Chirag Arora", site: "chiragarora.tech", handle: "iChiragArora" },
  { name: "opey", site: "opeyadeyemi.com", handle: "atropey" },
  { name: "Micaiah", site: "josephmaxwellson.com", handle: "jaywellson_jay" },
  { name: "Jyotsna", site: "jyotsnavenk.com", handle: "jyotsnavenk" },
  { name: "Roy Jad", site: "royjad.com", handle: "jad2222222" },
  { name: "Ryan Cassidy", site: "ryancassidy.io", handle: "rcssdy" },
  { name: "Daniel.dev", site: "0xdaniiel.space", handle: "0xDaniiel" },
  { name: "Amine Haouas", site: "amine-haouas.vercel.app", handle: "med_haouas" },
  { name: "Aviral", site: "heyaviral.com", handle: "aviralj02" },
  { name: "Adanna", site: "adxnna.design", handle: "Adxnna" },
  { name: "Muhammad Dani Asyrofi", site: "daniasyrofi.com", handle: "dani_asyrofi" },
  { name: "Panca", site: "adindamochamad.com", handle: "adindacq" },
  { name: "Prasad Ware", site: "prsd.dev", handle: "prasadtwts" },
  { name: "Thasanthan", site: "thasanthan.com", handle: "iamthasanthan" },
  { name: "Chad Nislow", site: "chadnislow.com", handle: "CNislow" },
  { name: "rayhan khilji", site: "rayhan.website", handle: "rayhankhilji" },
  { name: "Meta Mudhaleedu", site: "metamudhaleedu.com", handle: "MetaMudhaleedu" },
  { name: "Piyush Gambhir", site: "piyushgambhir.com", handle: "piyushgambhir_" },
  { name: "Harshit Singh", site: "harshitsingh.me", handle: "__harshitt__" },
  { name: "Hirusha", site: "hirusha.dev", handle: "iamhirusha" },
  { name: "Dinil", site: "dinilth.vercel.app", handle: "codebydinil" },
  { name: "Harrison", site: "harrisonerd.com", handle: "erd_harrison" },
  { name: "Piyush Choudhari", site: "piyushc.com", handle: "piyush_yip" },
  { name: "Pushpak Teja", site: "pushpakteja.com", handle: "Pushpakteja" },
  { name: "tim waldin", site: "tim.waldin.net", handle: "twaldin" },
  { name: "Allen", site: "alleneubank.com", handle: "alleneubank" },
  { name: "Mohamed Edder", site: "mohamededderyouch.me", handle: "edderstudio" },
  { name: "subhash", site: "slyezil.github.io/subhash-portfolio", handle: "slyezil" },
  { name: "Naveen Gumaste", site: "naveengumaste.me", handle: "Z0D404" },
  { name: "Brian Lovin", site: "brianlovin.com", handle: "brian_lovin" },
  { name: "Prateush Sharma", site: "prateushsharma.in", handle: "PrateushSharma" },
  { name: "Jay Ranpariya", site: "jdranpariya.com", handle: "JDRanpariya" },
  { name: "Abhishek Bhattacharjee", site: "growwithabhishek.com", handle: "i_am_bhatta" },
  { name: "Parth Sinha", site: "parthsinha.com", handle: "parth_sinha18" },
  { name: "David V. Kimball", site: "davidvkimball.com", handle: "davidvkimball" },
  { name: "Giray BATITURK", site: "giraybatiturk.com", handle: "giraybatiturk" },
  { name: "Nana Asante", site: "nanaasante.tech", handle: "asantenocturnal" },
  { name: "Ronny", site: "ronn.fun", handle: "viprhz" },
  { name: "nvnx.gwei", site: "nvnx.in", handle: "nvnxu" },
  { name: "yashas", site: "yash0.in", handle: "vortxfusion" },
  { name: "Aswin", site: "aswindevs.vercel.app", handle: "whitespaceeee" },
  { name: "LaLulu Studio", site: "luluwangyy.github.io/yueyi-wang-portfolio", handle: "Lalulu_create" },
  { name: "rahulsain", site: "rahulsain.com", handle: "Rahulsainlll" },
  { name: "James", site: "jseddon.com", handle: "jgseddon" },
  { name: "iamsaranhere", site: "sarankumar.space", handle: "iamsaranhere" },
  { name: "Leonardo Uchoa", site: "leouchoapedreira.com.br", handle: "leouchoap" },
  { name: "Nayli Naza", site: "nayli.ai", handle: "nayli_ai" },
  { name: "Ebra", site: "ebrar.dev", handle: "ebrardev" },
  { name: "Arthur Galvão", site: "arthurgalvao.work", handle: "arthurgalvaorl" },
  { name: "Rohan Vohra", site: "rohanvohra.xyz", handle: "rvohra18" },
  { name: "nev", site: "aaronnev.com", handle: "nevscape" },
  { name: "Sule", site: "suleman1412.de", handle: "suleman1412" },
  { name: "Hipinspire", site: "markobijelic.com", handle: "hipinspire" },
  { name: "Alec Freese", site: "alecfreese.com", handle: "AlecFreese" },
  { name: "dsaltaren", site: "dsaltaren.com", handle: "dsaltaren" },
  { name: "manish", site: "manish.framer.website", handle: "manjjann" },
  { name: "Ritik Parmar", site: "ritikparmar.site", handle: "ritikkparmar" },
  { name: "Jachi", site: "devjachi.xyz", handle: "DevJachi_" },
  { name: "Sebastien", site: "buche.dev", handle: "Console_buche" },
  { name: "Hal", site: "hallee.me", handle: "hal__lee" },
  { name: "Raktim", site: "raktimrajkalita.com", handle: "raktimrajkalita" },
  { name: "Rangga Hadi Putra", site: "ranggabiner.com", handle: "ranggabiner" },
  { name: "Aaron Peabody", site: "aaronpeabody.dev", handle: "callme_Peabody" },
  { name: "sonal", site: "sonaljaiswal.com", handle: "sonaljaiswaal" },
  { name: "Loki", site: "lok1.dev", handle: "lokidotdev" },
  { name: "Wistant", site: "wistant.vercel.app", handle: "iamwistant" },
  { name: "Samuel Tuoyo", site: "samueltuoyo.cm", handle: "TuoyoS26091" },
  { name: "Harjot", site: "harjotrana.com", handle: "harjjotsinghh" },
  { name: "Pin Chen", site: "pinchen.me", handle: "pinchenchong" },
  { name: "Andrew", site: "andrewmcgehee.com", handle: "andrewmcgehee" },
  { name: "Volkan", site: "volkanakielle.com", handle: "volkanakielle" },
  { name: "Kristof", site: "coastalfuturist.com", handle: "CoastalFuturist" },
  { name: "Sasi", site: "sasi.codes", handle: "sasicodes" },
  { name: "Himanshu Singh", site: "personallogs.vercel.app", handle: "hsnice16" },
  { name: "Vectris", site: "vectr.is", handle: "vectris" },
  { name: "yo⁷ 요섭", site: "yoyosub.com", handle: "yosub" },
  { name: "Mirko Freschi", site: "mirkofreschi.com", handle: "mirkofreschiDev" },
  { name: "Annieway", site: "draw.annieway.world", handle: "annieway2026" },
  { name: "Pavlo Nekrasov", site: "pavlonekrasov.com", handle: "pavlonekrasov" },
  { name: "Druids", site: "murphyusifo.com", handle: "druids01" },
  { name: "dane", site: "dane.gg", handle: "danewrx" },
  { name: "HimanshuM", site: "himanshum.com", handle: "HimanshuM685" },
  { name: "Kevin Wimer", site: "kevinwimer.com", handle: "kevinace" },
  { name: "Apoorv Khanna", site: "apoorvkhanna.com", handle: "token_wala" },
  { name: "David Solheim", site: "davidsolheim.com", handle: "davidtsolheim" },
  { name: "Jeff Needles", site: "jsneedles.com", handle: "jsneedles" },
  { name: "Leo Koesters", site: "leokoesters.com", handle: "LeoKoesters" },
  { name: "tyagi", site: "intothebuilderness.com", handle: "vb_tyagi" },
  { name: "alele", site: "byaleks.space", handle: "AleksC0l" },
  { name: "Abati Samuel", site: "abatisamuel.pro", handle: "AbatiSamuel" },
  { name: "Adrián Mato", site: "adrianmato.com", handle: "adrianmg" },
  { name: "DT!", site: "tolanidaniel.me", handle: "daniel_tolani_" },
  { name: "Praise Fabilola", site: "praisefabilola.com", handle: "praise_ai" },
  { name: "Vuk", site: "vuk.fyi", handle: "vukmx" },
  { name: "Luke", site: "lucasmalizia.xyz", handle: "0xlukem" },
  { name: "Daniel Sun", site: "danielsun.space", handle: "danielsun_ui" },
  { name: "div (fp32)", site: "divagr.com", handle: "divagr1925" },
  { name: "Sonny", site: "sonnylab.com", handle: "sonnylazuardi" },
  { name: "Leo", site: "mrlemoos.dev", handle: "leonardo_lemos" },
  { name: "Rachit Thakur", site: "rachitdesign.vercel.app", handle: "RachitThakur146" },
  { name: "Jitesh Ghanchi", site: "jeeiee.com", handle: "JiteshGhanchi" },
  { name: "Nitin", site: "nitinmagdum.vercel.app", handle: "iam__sentry" },
  { name: "Roberto H. Alsina", site: "ralsina.me", handle: "ralsina" },
  { name: "Agustin Acu", site: "acu.sh", handle: "akilastudiocom" },
  { name: "Sudhanshu", site: "sudhnsh.dev", handle: "sdhnsh16" },
  { name: "Franek", site: "fr4nek.github.io", handle: "fr4n9k_" },
  { name: "Marie Circé", site: "notes.mariedrouvin.com", handle: "circecreates" },
  { name: "Aastha Sahu", site: "aasthasahu-portfolio.vercel.app", handle: "AasthaSahu0818" },
  { name: "Aditya", site: "akoder.xyz", handle: "AdiKodez" },
  { name: "Amogh Sabarwal", site: "deadzolt.studio", handle: "deadzoltt" },
  { name: "Harsh", site: "harshdayal.dev", handle: "woah_hd" },
  { name: "Josh", site: "joshuagavu.com", handle: "JoshuaGavu" },
  { name: "Maaz", site: "maazx.dev", handle: "Maaztwts" },
  { name: "Aditya Ghai", site: "adityaghai07.github.io", handle: "aditya_ghai07" },
  { name: "Leo Curry", site: "lachkar.me", handle: "realbrainer" },
  { name: "Jeremy", site: "jeremytechie.com", handle: "jeremytechie" },
  { name: "Prajwal Raut", site: "prajwalr.space", handle: "honeybangerr" },
  { name: "Shubham", site: "shubhamxpawar.me", handle: "Shubhamxpawar" },
  { name: "Yoab", site: "yoab.framer.website", handle: "yoabadam" },
  { name: "Erik Nielsen", site: "sorkila.com", handle: "thepixelgrid" },
  { name: "Idris Gadi", site: "igadii.dev", handle: "igadii_X" },
  { name: "Hyhor", site: "hyhor.com", handle: "realhyhor" },
  { name: "Sujal", site: "hecodesforme.com", handle: "hecodesforme" },
  { name: "Tobiáš Volný", site: "tobiasvolny.vercel.app", handle: "gojanxd_" },
  { name: "Ismail Dudekula", site: "ismaildudekula.vercel.app", handle: "ismail_inma" },
  { name: "-1", site: "juanmnl.com", handle: "_juanmnl" },
  { name: "Niteesh Yadav", site: "niteeshyadav.com", handle: "Niteesh22" },
  { name: "Farhaj", site: "farhajshahid.com", handle: "FARHAJSHAHlD" },
  { name: "Saipratap", site: "pratapfolio.vercel.app", handle: "Saipratap121" },
  { name: "Daz", site: "devansh.aurat.ai", handle: "8Dazo" },
  { name: "Viggy", site: "viggysworld.com", handle: "viggyvas" },
  { name: "Akhil", site: "akhilkolla.com", handle: "AkhilKolla" },
  { name: "Hardik", site: "colehardik.in", handle: "coleHardik" },
  { name: "MxB", site: "mehulxbuilds.in", handle: "MehulxBuilds" },
  { name: "thesyphon.xyz", site: "ontheturntable.framer.website", handle: "Syphon_xyz" },
  { name: "JONNA", site: "jonna.framer.wiki", handle: "jonnaissance" },
  { name: "Cheeky_Beulah", site: "beulah.page", handle: "BeulahAkindiya" },
  { name: "Ashutosh Jha", site: "ashutosh887.in", handle: "ashutosh887_" },
  { name: "Shiven Singh", site: "shivensingh.com", handle: "iamshiven_singh" },
  { name: "Pengwu", site: "pengwu.dev", handle: "afkpengu" },
  { name: "Paavan", site: "paavandesign.com", handle: "p44v9n" },
  { name: "Paras Madan", site: "parasmadan.in", handle: "ParasMadan9" },
  { name: "Myles Marino", site: "mylesmarino.com", handle: "mylesmarino" },
  { name: "Soumyajit Mukherjee", site: "thelazydevhub.blogspot.com", handle: "sam9890smsm" },
  { name: "Luis Jay", site: "jay-portfolio-ecru.vercel.app", handle: "Luis_Jeyy" },
  { name: "Jeey", site: "nearly.me", handle: "jeeypit" },
  { name: "alex shapalov", site: "alexsh.dev", handle: "alxshp" },
  { name: "Francesco Vaglia", site: "francescovaglia.com", handle: "francescovaglia" },
  { name: "Pedro Duarte", site: "ped.ro", handle: "peduarte" },
  { name: "PRIMA", site: "afisolami.com", handle: "AFisolami" },
  { name: "Alex Giuseppe Ispas", site: "troubleshoot.design", handle: "agispas" },
  { name: "waseem", site: "waseemweb.com", handle: "wseemye" },
  { name: "Keshav Suman", site: "keshavsuman.com", handle: "keshavsuman96" },
  { name: "Vlad Shumov", site: "vladshumov.com", handle: "VladShumovv" },
  { name: "Rich Photography", site: "richphoto.io", handle: "richphotoio" },
  { name: "vyshnav", site: "vyshnav.xyz", handle: "vyshnav_xyz" },
  { name: "Vyne", site: "uchechidivine.com", handle: "therappertainer" },
  { name: "jordan", site: "jordangarcia.me", handle: "jordandotbuilds" },
  { name: "BlessingYoung", site: "blessingyoung.webflow.io", handle: "Blessingyoung_1" },
  { name: "Téo", site: "teogoulois.com", handle: "Teo_Goulois" },
  { name: "Natan Asrat Yilma", site: "natanasrat.com", handle: "NatanAsratYilma" },
  { name: "Soham Gurav", site: "sohmh.space", handle: "7smv25" },
  { name: "Capacity", site: "capacityportfolio.lovable.app", handle: "Iam_CAPACITY" },
  { name: "Jyothish VM", site: "jyothishvm.com", handle: "realmojojojo_" },
  { name: "fangming.li", site: "fangming.li", handle: "lushnis" },
  { name: "Khua", site: "madebykhua.com", handle: "madebykhua" },
  { name: "Darshan Gajara", site: "darshan.design", handle: "WeirdoWizard" },
  { name: "DeepakNess", site: "deepakness.com", handle: "DeepakNesss" },
  { name: "Dhiraj Arya", site: "dhirajarya.in", handle: "dhirajarya01" },
  { name: "aarit", site: "aaritshah.com", handle: "withaarit" },
  { name: "Ganesh", site: "heyganesh.in", handle: "heyganesh_in" },
  { name: "abror", site: "abboskhonov.uz", handle: "abboskhonovv" },
  { name: "Chris Andrews", site: "chrisandrews.xyz", handle: "kurissuuu" },
  { name: "Krish Kumar Chhabra", site: "krishchhabra.com", handle: "KrishChhabra25" },
  { name: "codie", site: "codie.sh", handle: "chodiecodie" },
  { name: "ScriptedFantasy", site: "tarotpepe.com", handle: "scrptdfntsy" },
  { name: "👀", site: "reallyupthere.com", handle: "rlyupthere" },
  { name: "Jazmín", site: "jazminli.com", handle: "jazminli57" },
  { name: "Imran Molla", site: "imranmolla.com", handle: "imran__molla" },
  { name: "Kaito", site: "kaitodev.com", handle: "_kaitodev" },
  { name: "Emily Lai", site: "emilylai.com", handle: "emilylai" },
  { name: "Kaguura", site: "kaguura.com", handle: "KaguuraGichuru" },
  { name: "ebuka", site: "promise-folio.vercel.app", handle: "promiseNotNull" },
  { name: "Robert Siński", site: "robertsinski.dev", handle: "robertsinskidev" },
  { name: "Sanjay", site: "sanjay.page", handle: "Sanjayyb7" },
  { name: "tryhard", site: "adriteyo-das.vercel.app", handle: "tryhard_26" },
  { name: "0x12345x0", site: "nabeeljaved.xyz", handle: "0x12345xO" },
  { name: "bukowskiiiiii", site: "bukowskiiiiii.uk", handle: "zhangru81770932" },
  { name: "Meriç Kalkan", site: "merickalkan.cv", handle: "0xBrokkr" },
  { name: "Akshat Bhaskar", site: "akshatb.com", handle: "aksbhaskar" },
  { name: "Shobhit Khurana", site: "shobhit.site", handle: "Shobhitkhuranaa" },
  { name: "Qasim", site: "qasim.fyi", handle: "qasimbizs" },
  { name: "Sugandha", site: "sugandhadesigns.me", handle: "Sugandhx_" },
  { name: "joyce", site: "joyce.land", handle: "henloitsjoyce" },
  { name: "iParamzvik", site: "vikramvissamsetti.work", handle: "iParamzvik" },
  { name: "Amrit Pal Singh", site: "amrit.art", handle: "amritpaldesign" },
  { name: "fuyo", site: "fuyofulo.com", handle: "fuyofulo" },
  { name: "talha sk", site: "talhask.com", handle: "thetalhashaik" },
  { name: "Prof king keys", site: "pharmweb3.com/portfolio", handle: "Profkingkeys" },
  { name: "Hitesh", site: "hiteshdevcom.vercel.app", handle: "hiteshxdev" },
  { name: "Boluwatife (Tife) Olayinka", site: "tifeolayinka.com", handle: "tife_olayinka" },
  { name: "Ghazi", site: "ghaziaryan.github.io/portfolio", handle: "GhazisGizmos" },
  { name: "aly", site: "alyvas.com", handle: "alyvas_" },
  { name: "Rakibul", site: "rakibulism.space", handle: "rakibulism" },
  { name: "Design Chief Priest", site: "chiefpriest.design", handle: "dnaijatechguy" },
  { name: "Toyo", site: "toyoscreativespace.xyz", handle: "toyobammy" },
  { name: "Lalit Singh", site: "lalitsingh.me", handle: "LalitBuild" },
  { name: "ajeet patel", site: "ajeetpatel.xyz", handle: "Iampatelajeet" },
  { name: "Paras", site: "luffytaro.me", handle: "ParasVerma7454" },
  { name: "melih", site: "melihozdemir.com", handle: "melihozdemir_" },
  { name: "Thich Quang Duc", site: "kidsclub.hatopress.net", handle: "hassytee" },
  { name: "Sloemo", site: "sloemo.me", handle: "Sloemo_dzn" },
  { name: "Piyush", site: "piyush.click", handle: "piyushstwt" },
  { name: "Paramveer Singh Bhele", site: "paramveerbhele.com", handle: "ParamveerBhele" },
  { name: "Aakash Reddy", site: "aakashreddy.com", handle: "aakashreddy" },
  { name: "Bhushan", site: "bhushanagrawal.vercel.app", handle: "Bhushan4work_" },
  { name: "Rostyslav Slobodianiuk", site: "ros-portfolio.vercel.app", handle: "EpochePause" },
  { name: "clement hugbo", site: "codemathics.design", handle: "codemathics" },
  { name: "Nay", site: "tech.nayansarania.com", handle: "naayann01" },
  { name: "Stephen Adeniji", site: "stephenadeniji.com", handle: "steevenadeniji" },
  { name: "Steven Webster", site: "webstersensei.ai", handle: "stevenjwebster" },
  { name: "Parminder Singh", site: "parminder.pro", handle: "360parminder" },
  { name: "mxq", site: "mxq.one", handle: "mxqmxqt" },
  { name: "hasan", site: "mnah.dev", handle: "mnah05" },
  { name: "Raja Niketh Reddy", site: "rajanikethreddy.com", handle: "rajanikethreddy" },
  { name: "Fekry Aiad", site: "fekryaiad.com", handle: "FekryAiad" },
  { name: "Bluelyf", site: "bluelyf.com", handle: "VusieMoses" },
  { name: "Arya Gorjipour", site: "aryagorjipour.com", handle: "Aryagorjipour" },
  { name: "Afolabi Sokeye", site: "afolabisokeye.vzy.io", handle: "SokeyeA" },
  { name: "Mateo Tomaszeuski", site: "mateo.tomaszeuski.com", handle: "MTomaszeuski" },
  { name: "Vladislav Ponomarev", site: "ponomarev.studio", handle: "PonomareVlad" },
  { name: "Ilir Neziri", site: "ilirneziri.com", handle: "IlirNeziri98" },
  { name: "joel.", site: "joelcsaji.com", handle: "bitwitjoe" },
  { name: "ssych", site: "ui.ssych.com", handle: "ssychui" },
  { name: "kachi", site: "kachi.framer.website", handle: "KachiMbaezue" },
  { name: "shivendra", site: "shivendra.cc", handle: "shibu0x" },
  { name: "Emma Twersky", site: "twerske.dev", handle: "twerske" },
  { name: "Usualguy", site: "divyanshudev.in", handle: "usualTechNerd" },
  { name: "Yoshik", site: "yoshik-pc.vercel.app", handle: "AskYoshik" },
  { name: "fay", site: "failennaselta.com", handle: "failennaselta" },
  { name: "Vladislav Siumbeli", site: "vladsiu.com", handle: "vladsiu" },
  { name: "Afnizar Nur Ghifari", site: "afnizarnur.com", handle: "afnizarnur" },
  { name: "SAI KIRAN", site: "imsaikirann.in", handle: "imSaikirann" },
  { name: "fuchai", site: "fuch.ai", handle: "Fuchai" },
  { name: "vansh", site: "vxnsh.dev", handle: "madebyvansh" },
  { name: "Jay", site: "sutharjay.com", handle: "sutharjay0" },
  { name: "Gursahb Singh", site: "gs-rumana.com", handle: "gs_rumana" },
  { name: "NOOM", site: "noom.sh", handle: "noominoid" },
  { name: "Eleli Ayub", site: "ayub.eleliafrika.com", handle: "eleliayub" },
  { name: "Nachi.", site: "nachi.design", handle: "nachidesigner" },
  { name: "Kenneth Dsouza", site: "ken.cv", handle: "Kenneth" },
  { name: "Yash Vishnoi", site: "yashvishnoi.site", handle: "Yash_Vishnoi7" },
  { name: "Naphier Awalie", site: "naphiernode.vercel.app", handle: "bagatata05" },
  { name: "Robinson Honour", site: "robinsonhonour.me", handle: "honour_can_code" },
  { name: "Siddhesh Singh", site: "siddheshkr.com", handle: "itssiddhesh" },
  { name: "Anish Hazra", site: "anishhazra.github.io", handle: "anish_codes" },
  { name: "Akash", site: "codeguyakash.in", handle: "codeguyakash" },
  { name: "Sayantan", site: "sayantan.sh", handle: "Sayantan317" },
  { name: "Sanskriti Bhatnagar", site: "bsanskriti.com", handle: "bsanskriti_" },
  { name: "tohirr", site: "tohirr.dev", handle: "_tohirr" },
  { name: "Thomas Lince", site: "teal-sea.com", handle: "tealsea90" },
  { name: "Arturo L. Gómez", site: "lgzarturo.com", handle: "algforge" },
  { name: "Shuvam", site: "shuvam.in", handle: "shuvx_" },
  { name: "AnTheM", site: "anthemhayek.com", handle: "anthemhayek" },
  { name: "Gading", site: "gading.dev", handle: "gading_coder" },
  { name: "reazn", site: "ruu.by", handle: "reazndev" },
  { name: "Gaurav Nardia", site: "gauravnardia.com", handle: "gaurav_nardia" },
  { name: "Christopher Yu", site: "christopheryu.com", handle: "christopheryuu_" },
  { name: "Jacob Jolibois", site: "jacobjolibois.com", handle: "jacobjolibois" },
  { name: "Siddhesh Kasat", site: "siddhesh-kasat-portfolio.vercel.app", handle: "__iamsiddhesh__" }
];
